//! Python's `random.Random`, reproduced exactly.
//!
//! CPython uses MT19937 seeded with `init_by_array`, builds a 53-bit float
//! from two 32-bit outputs, and derives its variates in pure Python. Porting
//! the same steps gives the *same stream*, so a workload generated here is
//! identical to one generated by `Disaggregated_Inference_Sim`.
//!
//! The variates call `ln` and `exp`. Those come from the platform's libm, as
//! they do in CPython, so the streams agree to the bit on the same platform
//! (tested on Linux/glibc); elsewhere, expect agreement to within an ulp.

const N: usize = 624;
const M: usize = 397;
const MATRIX_A: u32 = 0x9908_b0df;
const UPPER_MASK: u32 = 0x8000_0000;
const LOWER_MASK: u32 = 0x7fff_ffff;

/// `random.Random(seed)` for a non-negative integer seed.
#[derive(Clone)]
pub struct PyRandom {
    mt: [u32; N],
    mti: usize,
}

impl PyRandom {
    pub fn new(seed: u64) -> Self {
        // CPython splits abs(seed) into little-endian 32-bit words (at least one).
        let mut key = vec![seed as u32];
        if seed >> 32 != 0 {
            key.push((seed >> 32) as u32);
        }
        let mut r = PyRandom {
            mt: [0; N],
            mti: N + 1,
        };
        r.init_by_array(&key);
        r
    }

    fn init_genrand(&mut self, s: u32) {
        self.mt[0] = s;
        for i in 1..N {
            let prev = self.mt[i - 1];
            self.mt[i] = 1_812_433_253u32
                .wrapping_mul(prev ^ (prev >> 30))
                .wrapping_add(i as u32);
        }
        self.mti = N;
    }

    fn init_by_array(&mut self, key: &[u32]) {
        self.init_genrand(19_650_218);
        let (mut i, mut j) = (1usize, 0usize);
        for _ in 0..N.max(key.len()) {
            let prev = self.mt[i - 1];
            self.mt[i] = (self.mt[i] ^ (prev ^ (prev >> 30)).wrapping_mul(1_664_525))
                .wrapping_add(key[j])
                .wrapping_add(j as u32);
            i += 1;
            j += 1;
            if i >= N {
                self.mt[0] = self.mt[N - 1];
                i = 1;
            }
            if j >= key.len() {
                j = 0;
            }
        }
        for _ in 0..N - 1 {
            let prev = self.mt[i - 1];
            self.mt[i] = (self.mt[i] ^ (prev ^ (prev >> 30)).wrapping_mul(1_566_083_941))
                .wrapping_sub(i as u32);
            i += 1;
            if i >= N {
                self.mt[0] = self.mt[N - 1];
                i = 1;
            }
        }
        self.mt[0] = 0x8000_0000;
    }

    pub fn next_u32(&mut self) -> u32 {
        if self.mti >= N {
            for k in 0..N {
                let y = (self.mt[k] & UPPER_MASK) | (self.mt[(k + 1) % N] & LOWER_MASK);
                let mag = if y & 1 == 1 { MATRIX_A } else { 0 };
                self.mt[k] = self.mt[(k + M) % N] ^ (y >> 1) ^ mag;
            }
            self.mti = 0;
        }
        let mut y = self.mt[self.mti];
        self.mti += 1;
        y ^= y >> 11;
        y ^= (y << 7) & 0x9d2c_5680;
        y ^= (y << 15) & 0xefc6_0000;
        y ^ (y >> 18)
    }

    /// `random()`: a float in [0, 1) with 53 random bits.
    pub fn random(&mut self) -> f64 {
        let a = (self.next_u32() >> 5) as f64;
        let b = (self.next_u32() >> 6) as f64;
        (a * 67_108_864.0 + b) * (1.0 / 9_007_199_254_740_992.0)
    }

    /// `expovariate(lambd)`.
    pub fn expovariate(&mut self, lambd: f64) -> f64 {
        -(1.0 - self.random()).ln() / lambd
    }

    /// `normalvariate(mu, sigma)`: Kinderman and Monahan's ratio-of-uniforms method.
    pub fn normalvariate(&mut self, mu: f64, sigma: f64) -> f64 {
        let nv_magicconst = 4.0 * (-0.5f64).exp() / 2.0f64.sqrt();
        loop {
            let u1 = self.random();
            let u2 = 1.0 - self.random();
            let z = nv_magicconst * (u1 - 0.5) / u2;
            let zz = z * z / 4.0;
            if zz <= -u2.ln() {
                return mu + z * sigma;
            }
        }
    }

    /// `lognormvariate(mu, sigma)`.
    pub fn lognormvariate(&mut self, mu: f64, sigma: f64) -> f64 {
        self.normalvariate(mu, sigma).exp()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Reference values printed by CPython 3.12:
    //   r = random.Random(5); [r.random() for _ in range(3)]
    #[test]
    fn matches_cpython_random() {
        let mut r = PyRandom::new(5);
        assert_eq!(r.random(), 0.6229016948897019);
        assert_eq!(r.random(), 0.7417869892607294);
        assert_eq!(r.random(), 0.7951935655656966);
    }

    //   random.Random(0).random()  and  random.Random(2**40 + 7).random()
    #[test]
    fn matches_cpython_seeding() {
        assert_eq!(PyRandom::new(0).random(), 0.8444218515250481);
        assert_eq!(PyRandom::new((1 << 40) + 7).random(), 0.6137037779936511);
    }
}
